import { readdir, readFile, stat } from "node:fs/promises";
import { extname, join, relative, sep } from "node:path";
import { defaultIgnoredDirectories } from "./config";
import type { FileCategory, IndexedFile, SymbolInfo } from "../types";

const generatedPatterns = [
  /(^|\/)vendor\//,
  /(^|\/)node_modules\//,
  /(^|\/)dist\//,
  /(^|\/)build\//,
  /(^|\/)coverage\//,
  /(^|\/)opensrc\//,
  /(^|\/)bootstrap\/ssr\//,
  /(^|\/)public\/build\//,
  /\.min\.(js|css)$/,
  /package-lock\.json$/,
  /pnpm-lock\.yaml$/,
  /yarn\.lock$/,
  /bun\.lockb?$/,
];

export async function hasAnyFileWithExtension(root: string, extension: string): Promise<boolean> {
  let found = false;
  await walk(root, defaultIgnoredDirectories, async (path) => {
    if (extname(path) === extension) found = true;
    return !found;
  });
  return found;
}

export async function scanRepository(
  root: string,
  ignoredDirectories = defaultIgnoredDirectories,
): Promise<IndexedFile[]> {
  const files: IndexedFile[] = [];
  await walk(root, ignoredDirectories, async (absolutePath) => {
    const path = toRelative(root, absolutePath);
    const info = await stat(absolutePath);
    if (!info.isFile()) return true;
    if (info.size > 1_500_000) return true;
    const extension = extname(path);
    const language = languageFor(extension, path);
    const content = await readFile(absolutePath, "utf8").catch(() => "");
    const isTest = isTestPath(path);
    const isGenerated =
      generatedPatterns.some((pattern) => pattern.test(path)) ||
      content.slice(0, 200).includes("<auto-generated");

    files.push({
      path,
      extension,
      language,
      category: categorizeFile(path),
      sizeBytes: info.size,
      hash: await hashContent(content),
      mtimeMs: info.mtimeMs,
      isTest,
      isGenerated,
      symbols: extractSymbols(path, content),
    });
    return true;
  });
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

async function walk(
  root: string,
  ignoredDirectories: string[],
  visit: (path: string) => Promise<boolean>,
): Promise<void> {
  async function inner(dir: string): Promise<boolean> {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return true;
    }
    for (const entry of entries) {
      const absolute = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (ignoredDirectories.includes(entry.name)) continue;
        const keepGoing = await inner(absolute);
        if (!keepGoing) return false;
      } else {
        const keepGoing = await visit(absolute);
        if (!keepGoing) return false;
      }
    }
    return true;
  }
  await inner(root);
}

function toRelative(root: string, path: string): string {
  return relative(root, path).split(sep).join("/");
}

export function categorizeFile(path: string): FileCategory {
  if (path.startsWith("app/Models/")) return "model";
  if (path.startsWith("app/Http/Controllers/")) return "controller";
  if (path.startsWith("app/Http/Requests/")) return "request";
  if (path.startsWith("app/Http/Resources/")) return "resource";
  if (path.startsWith("app/Services/")) return "service";
  if (path.startsWith("app/Actions/")) return "action";
  if (path.startsWith("app/Jobs/")) return "job";
  if (path.startsWith("app/Notifications/")) return "notification";
  if (path.startsWith("app/Policies/")) return "policy";
  if (path.startsWith("app/Enums/")) return "enum";
  if (path.startsWith("database/migrations/")) return "migration";
  if (path.startsWith("database/factories/")) return "factory";
  if (path.startsWith("tests/Feature/")) return "feature-test";
  if (path.startsWith("tests/Unit/")) return "unit-test";
  if (path.startsWith("routes/")) return "route";
  if (path.startsWith("config/")) return "config";
  if (path.startsWith("resources/js/Pages/")) return "frontend-page";
  if (path.startsWith("resources/js/Components/") || path.startsWith("src/components/"))
    return "frontend-component";
  if (isTestPath(path)) return "test";
  return "unknown";
}

export function extractSymbols(path: string, content: string): SymbolInfo[] {
  if (path.endsWith(".php")) return extractPhpSymbols(content);
  if (/\.(ts|tsx|js|jsx|vue)$/.test(path)) return extractTypeScriptSymbols(content);
  return [];
}

function extractPhpSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const pattern = /\b(class|interface|trait|enum|function)\s+([A-Za-z_][A-Za-z0-9_]*)/;
  lines.forEach((line, index) => {
    const match = line.match(pattern);
    if (match?.[1] && match[2]) {
      symbols.push({ kind: match[1], name: match[2], lineStart: index + 1 });
    }
  });
  return symbols;
}

function extractTypeScriptSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const patterns = [
    /\bexport\s+class\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bexport\s+function\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bfunction\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\binterface\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\btype\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bconst\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/,
  ];
  lines.forEach((line, index) => {
    for (const pattern of patterns) {
      const match = line.match(pattern);
      if (match?.[1]) {
        symbols.push({ kind: symbolKind(pattern), name: match[1], lineStart: index + 1 });
        break;
      }
    }
  });
  return symbols;
}

function symbolKind(pattern: RegExp): string {
  const text = pattern.source;
  if (text.includes("class")) return "class";
  if (text.includes("function")) return "function";
  if (text.includes("interface")) return "interface";
  if (text.includes("type")) return "type";
  return "const";
}

function languageFor(extension: string, path: string): string {
  if (extension === ".php") return "php";
  if (extension === ".vue") return "vue";
  if (extension === ".ts" || extension === ".tsx") return "typescript";
  if (extension === ".js" || extension === ".jsx") return "javascript";
  if (extension === ".json") return "json";
  if (path.endsWith(".md")) return "markdown";
  return extension.replace(".", "") || "unknown";
}

function isTestPath(path: string): boolean {
  return (
    path.startsWith("tests/") ||
    /\.(test|spec)\.(ts|tsx|js|jsx)$/.test(path) ||
    path.endsWith("Test.php")
  );
}

async function hashContent(content: string): Promise<string> {
  const data = new TextEncoder().encode(content);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
