import { readdir, readFile, stat } from "node:fs/promises";
import { dirname, extname, join, normalize, relative, sep } from "node:path";
import { defaultIgnoredDirectories } from "./config";
import type { FileCategory, IndexedFile, SymbolInfo } from "../types";

const generatedPatterns = [
  /(^|\/)vendor\//,
  /(^|\/)node_modules\//,
  /(^|\/)dist\//,
  /(^|\/)build\//,
  /(^|\/)coverage\//,
  /(^|\/)opensrc\//,
  /(^|\/)bootstrap\/ssr\//,
  /(^|\/)public\/build\//,
  /\.min\.(js|css)$/,
  /package-lock\.json$/,
  /pnpm-lock\.yaml$/,
  /yarn\.lock$/,
  /bun\.lockb?$/,
];

export async function hasAnyFileWithExtension(root: string, extension: string): Promise<boolean> {
  let found = false;
  await walk(root, defaultIgnoredDirectories, async (path) => {
    if (extname(path) === extension) found = true;
    return !found;
  });
  return found;
}

export async function scanRepository(
  root: string,
  ignoredDirectories = defaultIgnoredDirectories,
): Promise<IndexedFile[]> {
  const files: Array<IndexedFile & { importSpecifiers: string[] }> = [];
  await walk(root, ignoredDirectories, async (absolutePath) => {
    const path = toRelative(root, absolutePath);
    const info = await stat(absolutePath);
    if (!info.isFile()) return true;
    if (info.size > 1_500_000) return true;
    const extension = extname(path);
    const language = languageFor(extension, path);
    const content = await readFile(absolutePath, "utf8").catch(() => "");
    const isTest = isTestPath(path);
    const isGenerated =
      generatedPatterns.some((pattern) => pattern.test(path)) ||
      content.slice(0, 200).includes("<auto-generated");

    files.push({
      path,
      extension,
      language,
      category: categorizeFile(path),
      sizeBytes: info.size,
      hash: await hashContent(content),
      mtimeMs: info.mtimeMs,
      isTest,
      isGenerated,
      symbols: extractSymbols(path, content),
      dependencies: [],
      importSpecifiers: extractImportSpecifiers(path, content),
    });
    return true;
  });
  const paths = new Set(files.map((file) => file.path));
  return files
    .map(({ importSpecifiers, ...file }) => ({
      ...file,
      dependencies: resolveDependencies(file.path, importSpecifiers, paths),
    }))
    .sort((a, b) => a.path.localeCompare(b.path));
}

async function walk(
  root: string,
  ignoredDirectories: string[],
  visit: (path: string) => Promise<boolean>,
): Promise<void> {
  async function inner(dir: string): Promise<boolean> {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return true;
    }
    for (const entry of entries) {
      const absolute = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (ignoredDirectories.includes(entry.name)) continue;
        const keepGoing = await inner(absolute);
        if (!keepGoing) return false;
      } else {
        const keepGoing = await visit(absolute);
        if (!keepGoing) return false;
      }
    }
    return true;
  }
  await inner(root);
}

function toRelative(root: string, path: string): string {
  return relative(root, path).split(sep).join("/");
}

export function categorizeFile(path: string): FileCategory {
  if (path.startsWith("app/Models/")) return "model";
  if (path.startsWith("src/Entity/")) return "model";
  if (path.startsWith("app/models/")) return "model";
  if (path.startsWith("app/Http/Controllers/")) return "controller";
  if (path.startsWith("src/Controller/")) return "controller";
  if (path.startsWith("app/controllers/")) return "controller";
  if (path.startsWith("app/Http/Requests/")) return "request";
  if (path.startsWith("app/Http/Resources/")) return "resource";
  if (path.endsWith("/serializers.py")) return "resource";
  if (path.startsWith("app/Services/")) return "service";
  if (path.startsWith("src/Service/")) return "service";
  if (path.startsWith("app/Actions/")) return "action";
  if (path.startsWith("app/Jobs/")) return "job";
  if (path.startsWith("app/Notifications/")) return "notification";
  if (path.startsWith("app/Policies/")) return "policy";
  if (path.startsWith("app/Enums/")) return "enum";
  if (path.startsWith("database/migrations/")) return "migration";
  if (path.startsWith("migrations/") && path.endsWith(".php")) return "migration";
  if (path.startsWith("db/migrate/")) return "migration";
  if (path.includes("/migrations/") && path.endsWith(".py")) return "migration";
  if (path.startsWith("database/factories/")) return "factory";
  if (path.startsWith("spec/factories/")) return "factory";
  if (path.startsWith("tests/Feature/")) return "feature-test";
  if (path.startsWith("tests/Unit/")) return "unit-test";
  if (path.startsWith("spec/")) return "test";
  if (path.startsWith("test/")) return "test";
  if (path.endsWith("/tests.py") || /(^|\/)test_[^/]+\.py$/.test(path)) return "test";
  if (path.startsWith("routes/")) return "route";
  if (path === "config/routes.rb") return "route";
  if (path.endsWith("/urls.py")) return "route";
  if (/^(app\/)?(api|routers)\//.test(path) && path.endsWith(".py")) return "api-route";
  if (/^(app\/)?blueprints\//.test(path) && path.endsWith(".py")) return "route";
  if (/^(internal|pkg)\/.*\/models?\//.test(path) && path.endsWith(".go")) return "model";
  if (/^(internal|pkg)\/.*\/handlers?\//.test(path) && path.endsWith(".go")) return "controller";
  if (/^(internal|pkg)\/.*\/middleware\//.test(path) && path.endsWith(".go")) return "middleware";
  if (/^(internal|pkg)\/.*\/services?\//.test(path) && path.endsWith(".go")) return "service";
  if (path.endsWith("/models.py")) return "model";
  if (path.endsWith("/views.py")) return "controller";
  if (path.endsWith("/forms.py")) return "request";
  if (path.endsWith("/settings.py")) return "config";
  if (path.startsWith("src/routes/") && !/\/\+(page|layout)\.(svelte|vue|ts|js)$/.test(path))
    return "api-route";
  if (path.startsWith("src/controllers/")) return "controller";
  if (path.startsWith("src/middleware/")) return "middleware";
  if (path.startsWith("src/handlers/")) return "action";
  if (path.startsWith("src/schemas/")) return "schema";
  if (path.endsWith(".module.ts") || path.endsWith(".module.js")) return "module";
  if (path.endsWith(".controller.ts") || path.endsWith(".controller.js")) return "controller";
  if (path.endsWith(".service.ts") || path.endsWith(".service.js")) return "service";
  if (path.endsWith(".resolver.ts") || path.endsWith(".resolver.js")) return "controller";
  if (path.startsWith("config/")) return "config";
  if (/^(app|src\/app)\/api\/.+\/route\.(ts|tsx|js|jsx)$/.test(path)) return "api-route";
  if (/^(app|src\/app)\/(.*\/)?(page|layout)\.(ts|tsx|js|jsx)$/.test(path)) return "frontend-page";
  if (/^(pages|src\/pages)\/.+\.(ts|tsx|js|jsx)$/.test(path)) return "frontend-page";
  if (path.startsWith("pages/")) return "frontend-route";
  if (path.startsWith("src/pages/")) return "frontend-route";
  if (path.startsWith("src/content/")) return "frontend-content";
  if (path.startsWith("app/routes/")) return "frontend-route";
  if (/^app\/root\.(ts|tsx|js|jsx)$/.test(path)) return "frontend-layout";
  if (path.startsWith("layouts/")) return "frontend-layout";
  if (path.startsWith("components/")) return "frontend-component";
  if (path.startsWith("composables/")) return "frontend-composable";
  if (path.startsWith("src/routes/")) {
    if (/\/\+layout\.(svelte|ts|js)$/.test(path)) return "frontend-layout";
    return "frontend-route";
  }
  if (path.startsWith("resources/js/Pages/")) return "frontend-page";
  if (
    path.startsWith("resources/js/Components/") ||
    path.startsWith("src/components/") ||
    path.startsWith("src/lib/components/")
  )
    return "frontend-component";
  if (/^(components|src\/components)\/.+\.(ts|tsx|js|jsx)$/.test(path)) return "frontend-component";
  if (/^(hooks|src\/hooks)\/use[A-Z].*\.(ts|tsx|js|jsx)$/.test(path)) return "frontend-hook";
  if (isTestPath(path)) return "test";
  return "unknown";
}

export function extractSymbols(path: string, content: string): SymbolInfo[] {
  if (path.endsWith(".php")) return extractPhpSymbols(content);
  if (path.endsWith(".rb")) return extractRubySymbols(content);
  if (path.endsWith(".py")) return extractPythonSymbols(content);
  if (path.endsWith(".go")) return extractGoSymbols(content);
  if (/\.(ts|tsx|js|jsx|vue|svelte|astro)$/.test(path)) return extractTypeScriptSymbols(content);
  return [];
}

export function extractImportSpecifiers(path: string, content: string): string[] {
  if (/\.(ts|tsx|js|jsx|vue|svelte|astro)$/.test(path)) return extractTypeScriptImports(content);
  if (path.endsWith(".php")) return extractPhpImports(content);
  return [];
}

function extractPhpSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const pattern = /\b(class|interface|trait|enum|function)\s+([A-Za-z_][A-Za-z0-9_]*)/;
  lines.forEach((line, index) => {
    const match = line.match(pattern);
    if (match?.[1] && match[2]) {
      symbols.push({ kind: match[1], name: match[2], lineStart: index + 1 });
    }
  });
  return symbols;
}

function extractRubySymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const pattern = /^\s*(class|module|def)\s+([A-Za-z_][A-Za-z0-9_:!?=]*)/;
  lines.forEach((line, index) => {
    const match = line.match(pattern);
    if (match?.[1] && match[2]) {
      symbols.push({ kind: match[1], name: match[2], lineStart: index + 1 });
    }
  });
  return symbols;
}

function extractPythonSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const pattern = /^\s*(class|def)\s+([A-Za-z_][A-Za-z0-9_]*)/;
  lines.forEach((line, index) => {
    const match = line.match(pattern);
    if (match?.[1] && match[2]) {
      symbols.push({ kind: match[1], name: match[2], lineStart: index + 1 });
    }
  });
  return symbols;
}

function extractGoSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const patterns = [
    /^\s*func\s+(?:\([^)]+\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(/,
    /^\s*type\s+([A-Za-z_][A-Za-z0-9_]*)\s+(struct|interface)\b/,
  ];
  lines.forEach((line, index) => {
    for (const pattern of patterns) {
      const match = line.match(pattern);
      if (match?.[1]) {
        symbols.push({ kind: match[2] ?? "function", name: match[1], lineStart: index + 1 });
        break;
      }
    }
  });
  return symbols;
}

function extractTypeScriptSymbols(content: string): SymbolInfo[] {
  const symbols: SymbolInfo[] = [];
  const lines = content.split("\n");
  const patterns = [
    /\bexport\s+class\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bexport\s+default\s+function\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bexport\s+function\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bfunction\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\binterface\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\btype\s+([A-Za-z_][A-Za-z0-9_]*)/,
    /\bconst\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/,
  ];
  lines.forEach((line, index) => {
    for (const pattern of patterns) {
      const match = line.match(pattern);
      if (match?.[1]) {
        symbols.push({ kind: symbolKind(pattern), name: match[1], lineStart: index + 1 });
        break;
      }
    }
  });
  return symbols;
}

function extractTypeScriptImports(content: string): string[] {
  const imports = new Set<string>();
  const patterns = [
    /\bimport\s+(?:type\s+)?(?:[^'"]+\s+from\s+)?["']([^"']+)["']/g,
    /\bexport\s+[^'"]+\s+from\s+["']([^"']+)["']/g,
    /\bimport\s*\(\s*["']([^"']+)["']\s*\)/g,
    /\brequire\s*\(\s*["']([^"']+)["']\s*\)/g,
  ];
  for (const pattern of patterns) {
    for (const match of content.matchAll(pattern)) {
      if (match[1]) imports.add(match[1]);
    }
  }
  return [...imports];
}

function extractPhpImports(content: string): string[] {
  const imports = new Set<string>();
  for (const match of content.matchAll(/^\s*use\s+([^;{]+);/gm)) {
    const name = match[1]?.trim();
    if (name && !name.includes("\\")) continue;
    if (name) imports.add(name);
  }
  return [...imports];
}

function resolveDependencies(path: string, imports: string[], paths: Set<string>): string[] {
  const resolved = new Set<string>();
  for (const specifier of imports) {
    const target = specifier.startsWith(".")
      ? resolveRelativeImport(path, specifier, paths)
      : resolvePhpNamespace(specifier, paths);
    if (target && target !== path) resolved.add(target);
  }
  return [...resolved].sort();
}

function resolveRelativeImport(path: string, specifier: string, paths: Set<string>): string | null {
  const base = toPosix(normalize(join(dirname(path), specifier)));
  const candidates = [
    base,
    `${base}.ts`,
    `${base}.tsx`,
    `${base}.js`,
    `${base}.jsx`,
    `${base}.vue`,
    `${base}.svelte`,
    `${base}.astro`,
    `${base}/index.ts`,
    `${base}/index.tsx`,
    `${base}/index.js`,
    `${base}/index.jsx`,
    `${base}/index.vue`,
    `${base}/index.svelte`,
    `${base}/index.astro`,
  ];
  return candidates.find((candidate) => paths.has(candidate)) ?? null;
}

function resolvePhpNamespace(specifier: string, paths: Set<string>): string | null {
  const trimmed = specifier.replace(/^\\+/, "");
  if (!trimmed.startsWith("App\\")) return null;
  const candidate = `${trimmed.replace(/^App\\/, "app\\").replaceAll("\\", "/")}.php`;
  return paths.has(candidate) ? candidate : null;
}

function toPosix(path: string): string {
  return path.split(sep).join("/");
}

function symbolKind(pattern: RegExp): string {
  const text = pattern.source;
  if (text.includes("class")) return "class";
  if (text.includes("function")) return "function";
  if (text.includes("interface")) return "interface";
  if (text.includes("type")) return "type";
  return "const";
}

function languageFor(extension: string, path: string): string {
  if (extension === ".php") return "php";
  if (extension === ".rb") return "ruby";
  if (extension === ".py") return "python";
  if (extension === ".go") return "go";
  if (extension === ".vue") return "vue";
  if (extension === ".svelte") return "svelte";
  if (extension === ".astro") return "astro";
  if (extension === ".ts" || extension === ".tsx") return "typescript";
  if (extension === ".js" || extension === ".jsx") return "javascript";
  if (extension === ".json") return "json";
  if (path.endsWith(".md")) return "markdown";
  return extension.replace(".", "") || "unknown";
}

function isTestPath(path: string): boolean {
  return (
    path.startsWith("tests/") ||
    path.startsWith("spec/") ||
    /^test\/.*_test\.rb$/.test(path) ||
    path.endsWith("/tests.py") ||
    path.endsWith("_test.go") ||
    /(^|\/)test_[^/]+\.py$/.test(path) ||
    /\.(test|spec)\.(ts|tsx|js|jsx)$/.test(path) ||
    path.endsWith("Test.php")
  );
}

async function hashContent(content: string): Promise<string> {
  const data = new TextEncoder().encode(content);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(hash)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
